<?php

/**
 * PluginndComponentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginndComponentsTable extends Doctrine_Table
{
    /*
     * Returns an instance of this class.
     *
     * @return object ndComponentsTable
     */
    public static function getInstance(){
        return Doctrine_Core::getTable('ndComponents');
    }
    
    /*
     * Get all Component order by created_at DESC
     * 
     * @return  object  $p
     */
    public function getComponent(){
        $p = $this->createQuery('p');
        return $p;
    }
    
    /*
     * Get all Components
     * 
     * @return   object  $p
     */
    public function getComponents(){
        $p = $this->getComponent();
        
        return $p;
    } 
}