<?php

/**
 * PluginndComponents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ndComponentsPlugin/lib
 * @subpackage model
 * @author     Dachez <X9> Nicolas <ndachez@epsi.fr>
 * @version    
 */
abstract class PluginndComponents extends BasendComponents
{
  public function changeStatus()
  {

    if(1 == $this->getActive())
    {
      $this->setActive(0);
    }
    elseif(0 == $this->getActive())
    {
      $this->setActive(1);
    }
    
    $this->save();
  }
}