<?php

/**
 * PluginndComponents
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ndComponentsPlugin/lib
 * @subpackage model
 * @author     Dachez <X9> Nicolas <ndachez@epsi.fr>
 * @version    
 */
abstract class PluginndComponents extends BasendComponents
{

}