generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ndComponents
    theme:                 peanut
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          nd_adminComponents
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      
      fields:  ~
      
      list:    
        
        title: "Components"
        
        display: [active, =title]
        
        actions:
        
        object_actions:
          "Change status":
            action: changestatus
          _edit:        ~
          _delete:      ~
          
        max_per_page:   15
        
      filter:
        display:           [title]
      
      form:
        display:
          "General":        [title]
          "Content":        [description, url]
          "Informations":   [active]
      
      edit:    
        title: "Modify this component"
      
      new:     
        title: "Add new component"